version: '3'

services:
  prometheus:
    image: ubuntu/prometheus:2.33-22.04_beta
    volumes:
      - /home/prithvi/jenkins-monitoring/docker-compose/prometheus/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.5.5
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000

  influxdb:
    image: influxdb:1.8.6-alpine
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - 8080:8080

